routes/web.php
<?php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('publications', 'PublicationsController')->middleware('auth');
Route::resource('comments', 'CommentsController')->middleware('auth');
Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');

app/Publication.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
class Publication extends Model
{
    //
    public function comment() {
        return $this->hasMany(Comment::class);
    }

    public function user() {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/PublicationsController.php
<?php

namespace App\Http\Controllers;

use App\Publication;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PublicationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       // $user = Publication::find(1)->user()->get();
       // echo $user[0]->email;
        $publications = Publication::all();
        return view('publications.index',compact('publications'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('publications.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=> 'required',
            'content' => 'required'
        ]);
        try{
            $publicar =new Publication;
            $publicar->title = $request->title;
            $publicar->content = $request->content;
            $publicar->user_id = Auth::user()->id;
            $publicar->save();
            return redirect()->route('publications.index')->with('success', 'Publicación creada exitosamente!');
        }catch(Exception $e){
            return redirect()->route('publications.index')->with('error', 'Error! no se pudo publicar!');
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $publication = Publication::find($id);
        $publication->comment()->get();
        $publication->load('comment');
        return view('publications.show', compact('publication'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('publications.edit', compact('publication'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/publications/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
         <h1>Realizar Publicación</h1>
        </div>
    </div>

    <form action="{{ route('publications.store') }}" method="POST">
    @csrf
    <div class="container">
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
            <strong>Título:</strong>
                <input class="form-control" name="title" placeholder="titulo"></input>
            </div>
            <div class="form-group">
                <strong>Content:</strong>
                <input class="form-control" style="height:150px" name="content" placeholder="content"></input>
            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Publicar</button>
        </div>
    </div>
    </div>
</form>
@endsection

resources/views/publications/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Publicaciones actuales</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('publications.create') }}"> Crear nueva publicación</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
     @if ($message = Session::get('error'))
        <div class="alert alert-danger">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>title</th>
            <th>Content</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($publications as $publication)
        <tr>
            <td>{{ $publication->id }}</td>
            <td>{{ $publication->title }}</td>
            <td>{{ $publication->content }}</td>
            <td>
                <a class="btn btn-info" href="{{ route('publications.show',$publication->id) }}">Ver comentarios</a>
            </td>
        </tr>
        @endforeach
    </table>

    </div>
@endsection

resources/views/publications/show.blade.php
@extends('layouts.app')
@section('content')
    <div class = "container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Comentarios</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('publications.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <ul class="list-group list-group-flush">
        @foreach ($publication->comment as $comment)
            @if($comment->status == "APROBADO")
            <li class="list-group-item">{{$comment->content}}</li>
            @endif
       @endforeach
        </ul>
    </div>

    <form action="{{ route('comments.store') }}" method="POST">
    @csrf
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <input class="form-control" name="publication_id" hidden="true" value="{{ $publication->id }}"></input>
            </div>
            <div class="form-group">
                <strong>Comment:</strong>
                <textarea class="form-control" style="height:150px" name="content" placeholder="Comment"></textarea>
            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Comment</button>
        </div>
    </div>
</form>
</div>
@endsection